[my_app]

description = "Replicates the Hydra Get Started example."
exec = "python my_app.py"

[my_app.sourcecode]

include = "**/*"

[my_app.config]

include = "conf/**/*.yaml"

[my_app.config.bind]

target = "*"
