[a]

description = "Shows progress for run phases"

[a.exec]

stage-sourcecode = """
echo Copying source code
sleep 1
"""

stage-runtime = """
echo Initialzing runtime
sleep 1
"""

stage-dependencies = """
echo Resolving dependencies
sleep 1
"""

run = """
python -u -c "
import time
for i in range(10):
    print(f'Step {i}')
    time.sleep(0.5)
"
"""

finalizing-run = """
echo Finalizing
sleep 1
"""
